apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-http
spec:
  selector:
    matchLabels:
      app: product-catalog-http
  template:
    metadata:
      labels:
        app: product-catalog-http
    spec:
      containers:
      - name: product-catalog-http
        image: registry.gitlab.com/gsissa/image-registry-repo/swop-product-catalog:0.1.0-SNAPSHOT
      imagePullSecrets:
        - name: gitlab-registry
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: product-catalog-http-svc
#spec:
#  selector:
#    app: product-catalog-http
#  ports:
#  - protocol: TCP
#    port: 8085