CREATE TABLE IF NOT EXISTS USERSTORE(
    AGE INT,
    ID VARCHAR (50),
    OCCUPATION VARCHAR (100),
    USERNAME VARCHAR (50),
    TYPEID VARCHAR (2),
    LOCATIONADRESS VARCHAR (50),
    LOCATIONCOUNTRY VARCHAR (50),
    LOCATIONCITY VARCHAR (50),
    LOCATIONZIPCODE VARCHAR (50)
)